<?php
namespace Proxies\__CG__\Application\DeskPRO\Entity;
/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class TicketMessage extends \Application\DeskPRO\Entity\TicketMessage implements \Doctrine\ORM\Proxy\Proxy
{
    protected $__entityPersister__;
	public $_dp_object_translatable;
    protected $__identifier__;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->__entityPersister__ = $entityPersister;
        $this->__identifier__ = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->__entityPersister__) {
            $this->__isInitialized__ = true;
            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }
            if ($this->__entityPersister__->load($this->__identifier__, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->__entityPersister__, $this->__identifier__);
        }
    }
    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }
    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->__identifier__["id"];
        }
        if ($this->__isInitialized__ === false) $this->__load();
        return parent::getId();
    }

    public function setTicketId($id)
    {
        if ($this->__isInitialized__ === false) $this->__load();
        return parent::setTicketId($id);
    }

    public function getTicketId()
    {
        if ($this->__isInitialized__ === false) $this->__load();
        return parent::getTicketId();
    }

    public function setPersonId($id)
    {
        if ($this->__isInitialized__ === false) $this->__load();
        return parent::setPersonId($id);
    }

    public function getPersonId()
    {
        if ($this->__isInitialized__ === false) $this->__load();
        return parent::getPersonId();
    }

    public function getMessageLength()
    {
        if ($this->__isInitialized__ === false) $this->__load();
        return parent::getMessageLength();
    }

    public function getMessageHtmlClipped($max_length)
    {
        if ($this->__isInitialized__ === false) $this->__load();
        return parent::getMessageHtmlClipped($max_length);
    }

    public function getMessageHtml()
    {
        if ($this->__isInitialized__ === false) $this->__load();
        return parent::getMessageHtml();
    }

    public function procInlineAttach($message)
    {
        if ($this->__isInitialized__ === false) $this->__load();
        return parent::procInlineAttach($message);
    }

    public function convertEmbeddedImagesToInlineAttach()
    {
        if ($this->__isInitialized__ === false) $this->__load();
        return parent::convertEmbeddedImagesToInlineAttach();
    }

    public function getUsedSignatureImageBlobs()
    {
        if ($this->__isInitialized__ === false) $this->__load();
        return parent::getUsedSignatureImageBlobs();
    }

    public function getMessageText()
    {
        if ($this->__isInitialized__ === false) $this->__load();
        return parent::getMessageText();
    }

    public function getMessageFull()
    {
        if ($this->__isInitialized__ === false) $this->__load();
        return parent::getMessageFull();
    }

    public function getMessagePlainHtml()
    {
        if ($this->__isInitialized__ === false) $this->__load();
        return parent::getMessagePlainHtml();
    }

    public function setMessageHtml($message)
    {
        if ($this->__isInitialized__ === false) $this->__load();
        return parent::setMessageHtml($message);
    }

    public function getMessageQuote()
    {
        if ($this->__isInitialized__ === false) $this->__load();
        return parent::getMessageQuote();
    }

    public function setMessageText($message)
    {
        if ($this->__isInitialized__ === false) $this->__load();
        return parent::setMessageText($message);
    }

    public function setMessage($message)
    {
        if ($this->__isInitialized__ === false) $this->__load();
        return parent::setMessage($message);
    }

    public function addAttachment(\Application\DeskPRO\Entity\TicketAttachment $attach)
    {
        if ($this->__isInitialized__ === false) $this->__load();
        return parent::addAttachment($attach);
    }

    public function setVisitor(\Application\DeskPRO\Entity\Visitor $visitor = NULL)
    {
        if ($this->__isInitialized__ === false) $this->__load();
        return parent::setVisitor($visitor);
    }

    public function setGeoCountry($geo_country)
    {
        if ($this->__isInitialized__ === false) $this->__load();
        return parent::setGeoCountry($geo_country);
    }

    public function getGeoCountry()
    {
        if ($this->__isInitialized__ === false) $this->__load();
        return parent::getGeoCountry();
    }

    public function setVisitorFromRequest()
    {
        if ($this->__isInitialized__ === false) $this->__load();
        return parent::setVisitorFromRequest();
    }

    public function isFromGateway()
    {
        if ($this->__isInitialized__ === false) $this->__load();
        return parent::isFromGateway();
    }

    public function getMessageHash()
    {
        if ($this->__isInitialized__ === false) $this->__load();
        return parent::getMessageHash();
    }

    public function initHashCode()
    {
        if ($this->__isInitialized__ === false) $this->__load();
        return parent::initHashCode();
    }

    public function initPersonAccessCode()
    {
        if ($this->__isInitialized__ === false) $this->__load();
        return parent::initPersonAccessCode();
    }

    public function incTicketCount()
    {
        if ($this->__isInitialized__ === false) $this->__load();
        return parent::incTicketCount();
    }

    public function getObjectRef()
    {
        if ($this->__isInitialized__ === false) $this->__load();
        return parent::getObjectRef();
    }

    public function setUntrackedModelField($field, $value)
    {
        if ($this->__isInitialized__ === false) $this->__load();
        return parent::setUntrackedModelField($field, $value);
    }

    public function toApiData($primary = true, $deep = true, array $visited = array (
))
    {
        if ($this->__isInitialized__ === false) $this->__load();
        return parent::toApiData($primary, $deep, $visited);
    }

    public function getScalarData()
    {
        if ($this->__isInitialized__ === false) $this->__load();
        return parent::getScalarData();
    }

    public function _setNoPersist()
    {
        if ($this->__isInitialized__ === false) $this->__load();
        return parent::_setNoPersist();
    }

    public function _isNoPersist()
    {
        if ($this->__isInitialized__ === false) $this->__load();
        return parent::_isNoPersist();
    }

    public function __toString()
    {
        if ($this->__isInitialized__ === false) $this->__load();
        return parent::__toString();
    }

    public function fromArray(array $values)
    {
        if ($this->__isInitialized__ === false) $this->__load();
        return parent::fromArray($values);
    }

    public function toArray($mode = 1)
    {
        if ($this->__isInitialized__ === false) $this->__load();
        return parent::toArray($mode);
    }

    public function getKeys()
    {
        if ($this->__isInitialized__ === false) $this->__load();
        return parent::getKeys();
    }

    public function getFieldKeys()
    {
        if ($this->__isInitialized__ === false) $this->__load();
        return parent::getFieldKeys();
    }

    public function propertyFieldExists($field)
    {
        if ($this->__isInitialized__ === false) $this->__load();
        return parent::propertyFieldExists($field);
    }

    public function get($name)
    {
        if ($this->__isInitialized__ === false) $this->__load();
        return parent::get($name);
    }

    public function set($name, $value)
    {
        if ($this->__isInitialized__ === false) $this->__load();
        return parent::set($name, $value);
    }

    public function __get($name)
    {
        if ($this->__isInitialized__ === false) $this->__load();
        return parent::__get($name);
    }

    public function __set($name, $value)
    {
        if ($this->__isInitialized__ === false) $this->__load();
        return parent::__set($name, $value);
    }

    public function __isset($name)
    {
        if ($this->__isInitialized__ === false) $this->__load();
        return parent::__isset($name);
    }

    public function __unset($name)
    {
        if ($this->__isInitialized__ === false) $this->__load();
        return parent::__unset($name);
    }

    public function __call($name, $arguments)
    {
        if ($this->__isInitialized__ === false) $this->__load();
        return parent::__call($name, $arguments);
    }

    public function offsetExists($offset)
    {
        if ($this->__isInitialized__ === false) $this->__load();
        return parent::offsetExists($offset);
    }

    public function offsetSet($offset, $value)
    {
        if ($this->__isInitialized__ === false) $this->__load();
        return parent::offsetSet($offset, $value);
    }

    public function offsetGet($offset)
    {
        if ($this->__isInitialized__ === false) $this->__load();
        return parent::offsetGet($offset);
    }

    public function offsetUnset($offset)
    {
        if ($this->__isInitialized__ === false) $this->__load();
        return parent::offsetUnset($offset);
    }

	public function __getPropValue__($k) { return $this->$k; }
	public function __setPropValue__($k, $v) { $this->$k = $v; }
	public function __hasRunLoad__() { if (isset($this->__entityPersister__)) return false; return true; }
    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'date_created', 'is_agent_note', 'creation_system', 'ip_address', 'geo_country', 'email', 'message_hash', 'message', 'message_full', 'message_raw', 'lang_code', 'show_full_hint', 'ticket', 'person', 'email_source', 'primary_translation', 'visitor', 'attachments');
    }
    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->__entityPersister__) {
            $this->__isInitialized__ = true;
            $class = $this->__entityPersister__->getClassMetadata();
            $original = $this->__entityPersister__->load($this->__identifier__);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->__entityPersister__, $this->__identifier__);
        }
        parent::__clone();
    }
}