<?php

namespace Application\DeskPRO\EntityRepository;

use Doctrine\ORM\EntityRepository;

/**
 * ImportMap
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImportMap extends AbstractEntityRepository
{
}